In [1]:
import plotly
from plotly.graph_objs import Scatter, Layout, Bar
# from pymongo import MongoClient
# client = MongoClient('127.0.0.1', 27017)
# db = client.influencers_db
# influencer_document = db.combined_collection.find_one({'tw_handle': 'MKBHD'})
# print(influencer_document)

influencer_document = "{'_id': ObjectId('5ab468eb7a8bda0f931b4759'), 'yt_url': 'https://www.youtube.com/user/marquesbrownlee', 'fb_page_likes': 298842, 'tw_location': 'NYC', 'ig_posts': '2', 'tw_tweets_file': 'twitter-data/MKBHD', 'tw_id_str': 29873662, 'fb_category': 'Technology', 'yt_view_count': 855393555, 'fb_handle': 'MKBHD', 'fb_state': '', 'yt_video_count': 995, 'fb_about': 'Entrepreneur  YouTube Partner  and Video Producer since 2008. http://youtube.com/MKBHD', 'ig_followers': '298', 'kl_score': '82.58831770499289', 'yt_channel_id': 'UCBJycsmduvYEL83R_U4JriQ', 'fb_website': 'http://youtube.com/MKBHD', 'tw_statuses_count': 41101, 'tw_handle': 'MKBHD', 'tw_name': 'Marques Brownlee', 'yt_title': 'Marques Brownlee', 'ig_following': '499', 'tw_followers_count': 2681731, 'yt_user_id': 'marquesbrownlee', 'tw_description': 'Web Video Producer | ⋈', 'tw_verified': 'True', 'yt_subscriber_count': 5876716, 'fb_name': 'Marques Brownlee', 'fb_country': '', 'ig_thumbnail_url': 'https://scontent-sea1-1.xx.fbcdn.net/v/t1.0-1/p200x200/15095027_1188901737822527_4758136153806777387_n.png?oh=112d2cda0a7a755be688ab3d5b60cff7&oe=5B38A50E', 'fb_city': '', 'ig_handle': 'MKBHD', 'tw_screen_name': 'MKBHD', 'kl_id': 832139}"


**Bar Plot : Follower count by channels**

In [2]:
import plotly.graph_objs as go
from plotly.graph_objs import Scatter, Layout, Bar

def bar_plot(x_list, y_list, vertical = True, title = '', barcolors = colors, 
             showYAxis = False, showYticks = False, showYticklabels = False, 
             showXAxis = False, showXticks = False, showXticklabels = False, 
             gridY = False, gridx = False):
    
    xaxisdict = dict(
        showline=True,
        showgrid=gridx,
        showticklabels=True,
        linecolor='rgb(204, 204, 204)',
        linewidth=2,
        autotick=False,
        ticks='outside',
        tickcolor='rgb(204, 204, 204)',
        tickwidth=2,
        ticklen=5,
        tickfont=dict(
            family='Arial',
            size=12,
            color='rgb(82, 82, 82)',
        ),
    )
    
    yaxisdict = dict(
            linecolor='rgb(204, 204, 204)',
            autorange=True,
            showgrid=gridY,
            zeroline=False,
            showline= showYAxis,
            autotick=True,
            ticks='outside',
            tick0=0,
            showticklabels= showYticklabels
        )
    
    layout = go.Layout(
        title = title,
        yaxis= yaxisdict if vertical else xaxisdict,
        xaxis= xaxisdict if vertical else yaxisdict,
        autosize=False,
        margin=dict(
            autoexpand=False,
            l=100,
            r=20,
            t=110,
        ),
        showlegend=False
    )
    
    
    trace0 = go.Bar(
        x=x_list,
        y=y_list,
        marker=dict(
            color= barcolors,
            line=dict(
                color='rgba(115,115,115, 0.5)',
                width=1.5,
            )
        ),
        opacity=0.6,
        orientation = 'v' if vertical else 'h'
    )
    
    plot = plotly.offline.plot({
    "data": [trace0], 
    'layout': layout
	}, output_type="div", include_plotlyjs=False, link_text="", show_link= False )
    return(plot)


################################################################################################
################################################################################################

# test
from IPython.core.display import HTML, display

tw_followers_count = influencer_document['tw_followers_count']
ig_followers = influencer_document['ig_followers']
yt_subscriber_count = influencer_document['yt_subscriber_count']
fb_page_likes = influencer_document['fb_page_likes']

values = [tw_followers_count, ig_followers, yt_subscriber_count, fb_page_likes]
labels = ['Twitter', 'Instagram', 'Youtube', 'Facebook']
colors = ['#1da1f280', '#8a3ab980', '#cc181e80', '#3b599880']

plot_v = bar_plot(x_list= labels, y_list = values, title = 'Followers Count Across Channels'
                , showYAxis = True, showYticklabels = True
                , barcolors = colors, vertical = True)

plot_h = bar_plot(x_list= values , y_list = labels, title = 'Followers Count Across Channels'
                , showYAxis = True, showYticklabels = True
                , barcolors = colors, vertical = False)

display(HTML(plot_h))
display(HTML(plot_v))



NameError: name 'colors' is not defined

In [3]:
import json
from IPython.core.display import HTML, display
plotly.offline.init_notebook_mode(connected=True)

tw_statuses_count = influencer_document['tw_statuses_count']
yt_video_count = influencer_document['yt_video_count']
ig_posts = influencer_document['ig_posts']


values = [tw_statuses_count, ig_posts, yt_video_count]
labels = ['Twitter', 'Instagram', 'Youtube']
colors = ['#1da1f280', '#8a3ab980', '#cc181e80']

plot_v = bar_plot(x_list= labels , y_list = values, title = 'Total Posts Across Channels'
                , showYAxis = True, showYticklabels = True
                , barcolors = colors, vertical = True)

display(HTML(plot_v))

TypeError: string indices must be integers

In [4]:
import json

plotly.offline.init_notebook_mode(connected=True)

tw_average_likes = 100
ig_average_likes = 120
yt_average_likes = 250

values = [tw_average_likes, ig_average_likes, yt_average_likes]
labels = ['Twitter', 'Instagram', 'Youtube']
colors = ['#1da1f280', '#8a3ab980', '#cc181e80']
hver_label = labels


def bubble_plot(x_list, radius, bubblecolors = '', title = '', hover_labels = ''):
    
    height_y = [max(radius) + 10]*len(radius)
    
    xaxisdict = dict(
        showline=True,
        showgrid=False,
        showticklabels=True,
        linecolor='rgb(204, 204, 204)',
        linewidth=2,
        autotick=False,
        ticks='outside',
        tickcolor='rgb(204, 204, 204)',
        tickwidth=2,
        ticklen=5,
        tickfont=dict(
            family='Arial',
            size=12,
            color='rgb(82, 82, 82)',
        ),
    )
    
    yaxisdict = dict(
            linecolor='rgb(204, 204, 204)',
            autorange=True,
            showgrid=False,
            zeroline=False,
            showline= False,
            autotick=True,
            ticks='',
            tick0=0,
            showticklabels= False
        )
    
    layout = go.Layout(
        title = title,
        yaxis= yaxisdict,
        xaxis= xaxisdict,
        autosize=True,
        margin=dict(
            autoexpand=False,
            l=100,
            r=20,
            t=110,
        ),
        showlegend=False
    )
    
    trace0 = go.Scatter(
        x=x_list,
        y=height_y,
        mode = 'markers',
        marker=dict(
            size = radius,
            color= bubblecolors,
            line=dict(
                color='rgba(115,115,115, 0.5)',
                width=1.5,
            )
        ),
        opacity=0.6,
        showlegend = False,
        hoverinfo='text',
        text = hover_labels
    )
    
    plot = plotly.offline.plot({
    "data": [trace0],
    'layout': layout
	}, output_type="div", include_plotlyjs=False, link_text="", show_link= False )
    
    return(plot)

b = bubble_plot(x_list = labels, radius = values, bubblecolors = colors, title = 'Average Comments',
               hover_labels = hver_label)
display(HTML(b))

In [4]:
import pandas as pd
import json

df = pd.read_json('input/ig_mkbhd', lines = True)
# print(df.head())


d = df.set_index('timestamp').groupby(pd.TimeGrouper('D')).mean().dropna()

h = df.set_index('timestamp').groupby(pd.TimeGrouper('H')).mean().dropna()
h_index = h.index
from datetime import datetime

hour_of_day = [hi.hour for hi in h_index]
# h.index = new_index
h['hour_of_day'] = hour_of_day
grouped = h.groupby('hour_of_day').count()
# h.head(10)
grouped

# activity = Scatter(x=grouped.index, y= grouped.comments, fill='tozeroy')
# plot5 = plotly.offline.iplot({
#     "data": [activity]
# 	})
# plot5

def line_plot(x_list, y_list, fill = False, 
              gridx= False, gridY= False, showYticklabels= True, showYAxis = True, title=''):
    
    xaxisdict = dict(
        showline=True,
        showgrid=gridx,
        showticklabels=True,
        linecolor='rgb(204, 204, 204)',
        linewidth=2,
        autotick=False,
        ticks='outside',
        tickcolor='rgb(204, 204, 204)',
        tickwidth=2,
        ticklen=5,
        tickfont=dict(
            family='Arial',
            size=12,
            color='rgb(82, 82, 82)',
        ),
    )
    
    yaxisdict = dict(
            linecolor='rgb(204, 204, 204)',
            autorange=True,
            showgrid=gridY,
            zeroline=False,
            showline= showYAxis,
            autotick=True,
            ticks='outside',
            tick0=0,
            showticklabels= showYticklabels
        )
    
    layout = go.Layout(
        title = title,
        yaxis= yaxisdict,
        xaxis= xaxisdict,
        autosize=False,
        margin=dict(
            autoexpand=False,
            l=100,
            r=20,
            t=110,
        ),
        showlegend=False
    )
    
    trace0 = Scatter(x=grouped.index, y= grouped.comments, fill='tozeroy' if fill else '')
    plot = plotly.offline.plot({
    "data": [trace0],
    'layout': layout
	},output_type="div", include_plotlyjs=False, link_text="", show_link= False)
    return(plot)

l = line_plot(grouped.index, grouped.comments, fill = False, title = 'Activity Over Hours')
display(HTML(l))

Test Graph::

In [23]:
import plotly.plotly as py
import plotly.graph_objs as go
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot

init_notebook_mode(connected=True)

def multi_line(x_data, y_data, labels, colors, title, x_axis_label, fill = False):
        
    x_count = len(x_data[0])
    mode_size = [8] * len(labels)
    line_size = [2] * len(labels)
    
    draw_fill = 'tozeroy' if fill else '' 
    traces = []
    for i in range(0, len(labels)):
        traces.append(go.Scatter(
            x = x_data[i],
            y = y_data[i],
            mode='lines+markers',
            line=dict(color=colors[i], width=line_size[i]),
            connectgaps=True,
            fill=draw_fill,
            hoverinfo='all',
            name= labels[i]
        ))

#         traces.append(go.Scatter(
#             x=[x_data[i][0], x_data[i][x_count -1]],
#             y=[y_data[i][0], y_data[i][x_count-1]],
#             mode='markers',
#             marker=dict(color=colors[i], size=mode_size[i]),
#             hoverinfo='none'
#         ))

    layout = go.Layout(
        xaxis=dict(
            range = [0, x_count -1],
            zeroline = False,
            showline=True,
            showgrid=False,
            showticklabels=True,
            linecolor='rgb(204, 204, 204)',
            linewidth=2,
            autotick=False,
            ticks='outside',
            tickcolor='rgb(204, 204, 204)',
            tickwidth=2,
            ticklen=5,
            tickfont=dict(
                family='Arial',
                size=12,
                color='rgb(82, 82, 82)',
            ),
        ),
        yaxis= dict(
            title='Activity',
            titlefont=dict(family='Arial',size=12, color='rgb(150,150,150)'),
            linecolor='rgb(204, 204, 204)',
            autorange=True,
            showgrid=False,
            zeroline=False,
            showline=False,
            autotick=False,
            ticks='',
            showticklabels=False,
        ),
        autosize=True,
        margin=dict(
            autoexpand=False,
            l=100,
            r=40,
            t=110,
        ),
        showlegend=True
    )

    annotations = []

    # Adding labels
#     for y_trace, label, color in zip(y_data, labels, colors):
#         # labeling the left_side of the plot
#         annotations.append(dict(xref='paper', x=0.05, y=y_trace[0] + 5,
#                                       xanchor='right', yanchor='middle',
#                                       text=label + ' {}'.format(y_trace[0]),
#                                       font=dict(family='Arial',
#                                                 size=16,
#                                                 color=colors,),
#                                       showarrow=False))
#         # labeling the right_side of the plot
#         annotations.append(dict(xref='paper', x=0.95, y=y_trace[x_count -1],
#                                       xanchor='left', yanchor='middle',
#                                       text=' {}'.format(y_trace[x_count -1]),
#                                       font=dict(family='Arial',
#                                                 size=16,
#                                                 color=colors,),
#                                       showarrow=False))
    # Title
    annotations.append(dict(xref='paper', yref='paper', x=0.0, y=1.05,
                                  xanchor='left', yanchor='bottom',
                                  text=title,
                                  font=dict(family='Arial',
                                            size=30,
                                            color='rgb(37,37,37)'),
                                  showarrow=False))
    # Source
    annotations.append(dict(xref='paper', yref='paper', x=0.5, y=-0.1,
                                  xanchor='center', yanchor='top',
                                  text= x_axis_label,
                                  font=dict(family='Arial',
                                            size=12,
                                            color='rgb(150,150,150)'),
                                  showarrow=False))

    layout['annotations'] = annotations
    
    plot = plotly.offline.plot({
    "data": traces,
    'layout': layout
	}, output_type="div", include_plotlyjs=False, link_text="", show_link= False )
    return(plot)


# test

title = 'Activity Over Hours'
labels = ['Facebook', 'Twitter', 'Instagram', 'Youtube']
colors = ['#3b599880', '#1da1f280', '#8a3ab980', '#cc181e80']


x_data = [
    list(range(0,24)),
    list(range(0,24)),
    list(range(0,24)),
    list(range(0,24)),
]


y_data = [
    [74, 82, 80, 74, 73, 72, 74, 70, 70, 66, 66, 69, 74, 82, 80, 74, 73, 72, 74, 70, 70, 66, 66, 69],
    [45, 42, 50, 46, 36, 36, 34, 35, 32, 31, 31, 28, 45, 42, 50, 46, 36, 36, 34, 35, 32, 31, 31, 28],
    [13, 14, 20, 24, 20, 24, 24, 40, 35, 41, 43, 50, 13, 14, 20, 24, 20, 24, 24, 40, 35, 41, 43, 50],
    [18, 21, 18, 21, 16, 14, 13, 18, 17, 16, 19, 23, 18, 21, 18, 21, 16, 14, 13, 18, 17, 16, 19, 23],
]

x = [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23], 
     [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23], 
     [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]]
y = [[11, 0, 2, 0, 5, 16, 35, 52, 41, 20, 43, 22, 36, 23, 33, 25, 24, 21, 24, 24, 7, 19, 10, 7], 
     [24, 21, 35, 23, 26, 25, 23, 4, 2, 1, 6, 6, 4, 23, 35, 45, 23, 38, 24, 17, 23, 28, 25, 19], 
     [1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 2, 3, 2, 0, 54, 35]] 
print(len(x[0]))

# m_l = multi_line(x_data= x_data, y_data = y_data, labels = labels, colors = colors, title = title)
# m_l = multi_line(x_data= x_data[0:3], y_data = y_data[0:3], labels = labels[0:3], 
#                  colors = colors[0:3], title = title, x_axis_label = 'Hours', fill = True)
m_l = multi_line(x_data= x, y_data = y, labels = labels[0:3], 
                 colors = colors[0:3], title = title, x_axis_label = 'Hours', fill = True)
display(HTML(m_l))

24


**HeatMap : Categorical x vs Categorical y, continuos Z**


In [6]:
import plotly
from IPython.core.display import HTML, display
import plotly.plotly as py
import plotly.graph_objs as go
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
from random import shuffle

init_notebook_mode(connected=True)

def heat_map(x, y, z, title = '', colorscale = 'YlGnBu'):
    trace0 = go.Heatmap(
        z=z,
        y=y,
        x=x,
        colorscale= colorscale,
    )
    
    layout = go.Layout(
        title = title,
    xaxis=dict(
        autotick=False,
        ticks='outside',
        dtick= 1.0
        )
    )

    plot = plotly.offline.plot({
        "data": [trace0],
        "layout":layout,
        }, output_type="div", include_plotlyjs=False, link_text="", show_link= False )
    return(plot)

#test

# This is the list of Plotly colorscales:
# [‘Blackbody’,
# ‘Bluered’,
# ‘Blues’,
# ‘Earth’,
# ‘Electric’,
# ‘Greens’,
# ‘Greys’,
# ‘Hot’,
# ‘Jet’,
# ‘Picnic’,
# ‘Portland’,
# ‘Rainbow’,
# ‘RdBu’,
# ‘Reds’,
# ‘Viridis’,
# ‘YlGnBu’,
# ‘YlOrRd’]

y =['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
# y=['Morning', 'Afternoon', 'Evening']

x = list(range(0,24))

# z is a list of size y of list of size of x (z = array of x*y)
# z=[[1, 20, 30, 50, 1], [20, 1, 60, 80, 30], [30, 60, 1, -10, 20]]
z = [
    [74, 82, 80, 74, 73, 72, 74, 70, 70, 66, 66, 69, 74, 82, 80, 74, 73, 72, 74, 70, 70, 66, 66, 69],
    [45, 42, 50, 46, 36, 36, 34, 35, 32, 31, 31, 28, 45, 42, 50, 46, 36, 36, 34, 35, 32, 31, 31, 28],
    [13, 14, 20, 24, 20, 24, 24, 40, 35, 41, 43, 50, 13, 14, 20, 24, 20, 24, 24, 40, 35, 41, 43, 50],
    [18, 21, 18, 21, 16, 14, 13, 18, 17, 16, 19, 23, 18, 21, 18, 21, 16, 14, 13, 18, 17, 16, 19, 23],
    [18, 21, 18, 21, 16, 14, 13, 18, 17, 16, 19, 23, 18, 21, 18, 21, 16, 14, 13, 18, 17, 16, 19, 23],
    [18, 21, 18, 21, 16, 14, 13, 18, 17, 16, 19, 23, 18, 21, 18, 21, 16, 14, 13, 18, 17, 16, 19, 23],
    [18, 21, 18, 21, 16, 14, 13, 18, 17, 16, 19, 23, 18, 21, 18, 21, 16, 14, 13, 18, 17, 16, 19, 23],
]

shuffle(z)
print(z)
h_m = heat_map(x,y,z, title = 'Activity Over Months', 
               colorscale=[[0.0, 'rgb(49,54,149)'], [0.5, 'rgb(224,243,248)'], [1.0, 'rgb(165,0,38)']])
display(HTML(h_m))



[[45, 42, 50, 46, 36, 36, 34, 35, 32, 31, 31, 28, 45, 42, 50, 46, 36, 36, 34, 35, 32, 31, 31, 28], [18, 21, 18, 21, 16, 14, 13, 18, 17, 16, 19, 23, 18, 21, 18, 21, 16, 14, 13, 18, 17, 16, 19, 23], [18, 21, 18, 21, 16, 14, 13, 18, 17, 16, 19, 23, 18, 21, 18, 21, 16, 14, 13, 18, 17, 16, 19, 23], [18, 21, 18, 21, 16, 14, 13, 18, 17, 16, 19, 23, 18, 21, 18, 21, 16, 14, 13, 18, 17, 16, 19, 23], [18, 21, 18, 21, 16, 14, 13, 18, 17, 16, 19, 23, 18, 21, 18, 21, 16, 14, 13, 18, 17, 16, 19, 23], [13, 14, 20, 24, 20, 24, 24, 40, 35, 41, 43, 50, 13, 14, 20, 24, 20, 24, 24, 40, 35, 41, 43, 50], [74, 82, 80, 74, 73, 72, 74, 70, 70, 66, 66, 69, 74, 82, 80, 74, 73, 72, 74, 70, 70, 66, 66, 69]]


In [30]:
import random

# random.sample(range(1, 100), 200)
# random.shuffle(range(1,100))


def chunks(l, n):
    """Yield successive n-sized chunks from l."""
    for i in range(0, len(l), n):
        yield l[i:i + n]



y = ['January', 'February', 'March', 'April', 'May', 'June', 'July',
              'August', 'September', 'October', 'November', 'December']
x = list(range(1,31))

l = [random.randint(50,500) for x in range( len(y)*len(x))]
z = list(chunks(l,len(x)))
h_m = heat_map(x,y,z, title = 'Activity Over Months', 
               colorscale= [[0.0, 'rgb(49,54,149)'], [0.5, 'rgb(224,243,248)'], [1.0, 'rgb(165,0,38)']] )
display(HTML(h_m))

Another test: 

In [50]:
import plotly.plotly as py
import plotly.figure_factory as ff

import numpy as np
import pandas as pd

from plotly.graph_objs import *

dataframe = pd.DataFrame(np.random.randn(100, 3),
                         columns=['Column A', 'Column B', 'Column C'])

fig = ff.create_scatterplotmatrix(dataframe, diag='histogram',index='Column A',
                                  colormap='Blues', height=800, width=800)

print(np.random.randn(10, 3))
iplot(fig)

# plot = plotly.offline.plot({
#     "data": fig,
# }, output_type="div", include_plotlyjs=False, link_text="", show_link= False )

# display(HTML(plot))

[[ 0.27722076 -1.92550375  1.82440075]
 [ 0.98153496  1.20236212  1.30966512]
 [-1.30777526  0.99714786  0.22297662]
 [-0.04749487  0.64070509 -1.23240005]
 [-0.57167308  0.92269401  0.54420094]
 [ 2.45132242  0.25433942  0.63523885]
 [ 1.04781525  0.46502646  0.44218401]
 [ 0.75494574  1.79268676  0.6517999 ]
 [ 0.06611351 -0.16576905  0.3847431 ]
 [ 1.07880255 -0.70011734  0.02321231]]


In [71]:
import plotly.plotly as py
import plotly.graph_objs as go
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot

def plotWaterfall(x_data, positives, negatives, bases):

    # Base
    trace0 = go.Bar(
        x=x_data,
        y = bases,
        marker=dict(
            color='rgba(1,1,1, 0.0)',
        )
    )
    # Revenue
    trace1 = go.Bar(
        x=x_data,
        y = positives,
        marker=dict(
            color='#2db24a'
        )
    )
    # Costs
    trace2 = go.Bar(
        x=x_data,
        y= negatives,
        marker=dict(
            color='#C45B15'
        )
    )


    data = [trace0, trace1, trace2]
    layout = go.Layout(
        title='Annual Profit- 2015',
        barmode='stack',
        showlegend=False
    )


    fig = go.Figure(data=data, layout=layout)
#     iplot(fig)
    
    
    plot = plotly.offline.plot({
        "data": data,
        "layout": layout
    }, output_type="div", include_plotlyjs=False, link_text="", show_link= False )

    HTML(plot)

In [72]:
x_data = ['Mar 30', 'Mar 31', 'Apr 01', 'Apr 02', 'Apr 03', 'Apr 04', 'Apr 05'] 
positives = [493.0, 197.0, 29.0, 387.0, 0, 606.0, 519.0, 40.0]
negatives = [0, 0, 0, 0, -95.0, 0, 0, 0]
bases = [0.0, 493.0, 690.0, 719.0, 1106.0, 1011.0, 1617.0]

plotWaterfall(x_data, positives, negatives, bases)